### PR TITLE
Docker 2

### LINKED ISSUE #26: Error in setup using Docker both in MacOS and Ubuntu
Used docker guide to setup the project. Getting  an error. Tried both in Ubuntu and MacOS. Getting the same error as shown in the image. 
error_installation

### PR DESCRIPTION
**Pull request by tmcw**
- Improves the Docker file to work on heterogenous host / guest combinations. Previously, afaict, we were using `node_modules` from the host _in_ the guest.
- Remove deprecated Next.js flag, `legacyBrowsers`. Doesn't seem like they have a replacement, so alas, we'll have to ship polyfills.
- Moves the Dockerfile to `dev.Dockerfile` so it isn't auto-detected by hosting platforms.
- Fixes #26

### CODE REVIEW

**Comment by anup39** [comment]
I pulled the changes, but it still did not work. I was encountering the same error, indicating that Blitz was not found. I suspected that the issue was not related to the host. Although the Node dependencies were installed, they were not executable. To address this, I added the path to the Node module, changed the ownership of the working directory, and installed some OS dependencies. Following these adjustments, the issue was resolved, and the application is now functioning properly. Not production ready but can be used for development.

**Comment by tmcw** [comment]
I think more detail is really required to debug this: on my machine, I'm running

```
docker compose build
docker compose up
```

And it's working. If there's something else going on, full error logs & commands are going to be needed to debug it.

**Comment by tmcw** [comment]
It looks like this Docker file is still reusing node_modules from the host system 🤦 . Docker experts welcome to chime in with a better way to do this, the apparent options are like, mounting directories one by one, or trying to exclude that directory, or moving everything into src?

**Comment by anup39** [comment]
Strange . I tried not only in my machine but also  in different ubuntu server i get the same issue.  it was unable to execute `blitz dev`. I can  push my changes in new branch called docker-dev , if you allow me. Its works now i have test in different manchine. Let me know.

**Comment by anup39** [comment]
> It looks like this Docker file is still reusing node_modules from the host system 🤦 . Docker experts welcome to chime in with a better way to do this, the apparent options are like, mounting directories one by one, or trying to exclude that directory, or moving everything into src?

"We can ignore the 'node_modules' from the host using .dockerignore. Wouldn't this solution resolve the issues?"

**Comment by anup39** [comment]
dev.Dockerfile:

`FROM node:20-slim
ENV NODE_ENV=development

WORKDIR /home/node/app

ENV PATH /home/node/app/node_modules/.bin:$PATH

RUN apt-get update && apt-get install -y openssl --no-install-recommends \
  &&  rm -rf /var/lib/apt/lists/* \
  && chown -R node:node /home/node/app

# Blitz.js recommends using tini, see why: https://github.com/krallin/tini/issues/8
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

USER node

# Install dependencies based on the preferred package manager
COPY  --chown=node:node package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn config list && yarn install --frozen-lockfile && yarn cache clean --force; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  # Allow install without lockfile, so example works even without Node.js installed locally
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

# TODO: this would be nice to change. Like,
# moving source to src
COPY --chown=node:node  . .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

ENTRYPOINT ["/tini", "--"]

# Start Next.js in development mode based on the preferred package manager
CMD \
  if [ -f yarn.lock ]; then yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
  else npm run dev; \
  fi
`

docker-compose.yml

`services:
  db:
    image: postgres:16.1
    restart: always
    env_file:
      - .env.local
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web: &web
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app
    user: node
    command: /bin/sh -c 'blitz prisma migrate deploy  && blitz prisma generate && yarn dev'
    ports:
      - 3000:3000
    depends_on:
      - db
  prisma:
    <<: *web
    command: >
      /bin/sh -c '
        yarn prisma migrate dev &&
        yarn studio
      '
    ports:
      - 5555:5555

volumes:
  db:
    driver: local
`

This now works from me . If anyone got the problem  in future then  you can try this. Thanks.

**Comment by anup39** [comment]
This configuration works for me. If any one have problem in future try this. Thanks. 

dev.Dockerfile

`FROM node:20-slim
ENV NODE_ENV=development

WORKDIR /home/node/app

ENV PATH /home/node/app/node_modules/.bin:$PATH

RUN apt-get update && apt-get install -y openssl --no-install-recommends \
  &&  rm -rf /var/lib/apt/lists/* \
  && chown -R node:node /home/node/app

# Blitz.js recommends using tini, see why: https://github.com/krallin/tini/issues/8
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

USER node

# Install dependencies based on the preferred package manager
COPY  --chown=node:node package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn config list && yarn install --frozen-lockfile && yarn cache clean --force; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  # Allow install without lockfile, so example works even without Node.js installed locally
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

# TODO: this would be nice to change. Like,
# moving source to src
COPY --chown=node:node  . .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

ENTRYPOINT ["/tini", "--"]

# Start Next.js in development mode based on the preferred package manager
CMD \
  if [ -f yarn.lock ]; then yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
  else npm run dev; \
  fi
`

docker-compose.yml 

`services:
  db:
    image: postgres:16.1
    restart: always
    env_file:
      - .env.local
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web: &web
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app
    user: node
    command: /bin/sh -c 'blitz prisma migrate deploy  && blitz prisma generate && yarn dev'
    ports:
      - 3000:3000
    depends_on:
      - db
  prisma:
    <<: *web
    command: >
      /bin/sh -c '
        yarn prisma migrate dev &&
        yarn studio
      '
    ports:
      - 5555:5555

volumes:
  db:
    driver: local
`

**Comment by anup39** [comment]
This solution worked for me. If anyone encounters a similar issue in the future, feel free to give this a try. Thanks!

dev.Dockerfile 

```
FROM node:20-slim
ENV NODE_ENV=development

WORKDIR /home/node/app

ENV PATH /home/node/app/node_modules/.bin:$PATH

RUN apt-get update && apt-get install -y openssl --no-install-recommends \
  &&  rm -rf /var/lib/apt/lists/* \
  && chown -R node:node /home/node/app

# Blitz.js recommends using tini, see why: https://github.com/krallin/tini/issues/8
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

USER node

# Install dependencies based on the preferred package manager
COPY  --chown=node:node package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn config list && yarn install --frozen-lockfile && yarn cache clean --force; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  # Allow install without lockfile, so example works even without Node.js installed locally
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

# TODO: this would be nice to change. Like,
# moving source to src
COPY --chown=node:node  . .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

ENTRYPOINT ["/tini", "--"]

# Start Next.js in development mode based on the preferred package manager
CMD \
  if [ -f yarn.lock ]; then yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
  else npm run dev; \
  fi

```

**Comment by anup39** [comment]
docker-compose.yml


```
services:
  db:
    image: postgres:16.1
    restart: always
    env_file:
      - .env.local
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web: &web
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app
    user: node
    command: /bin/sh -c 'blitz prisma migrate deploy  && blitz prisma generate && yarn dev'
    ports:
      - 3000:3000
    depends_on:
      - db
  prisma:
    <<: *web
    command: >
      /bin/sh -c '
        yarn prisma migrate dev &&
        yarn studio
      '
    ports:
      - 5555:5555

volumes:
  db:
    driver: local

```

**Comment by tmcw** [comment]
Sadly this doesn't work on my (OrbStack-based) Docker setup

```
web-1     | OrbStack ERROR: Dynamic loader not found: /lib64/ld-linux-x86-64.so.2
web-1     |
web-1     | This usually means that you're running an x86 program on an arm64 OS without multi-arch libraries.
web-1     | To fix this, you can:
web-1     |   1. Use an Intel (amd64) container to run this program; or
web-1     |   2. Install multi-arch libraries in this container.
web-1     |
web-1     | This can also be caused by running a glibc executable in a musl distro (e.g. Alpine), or vice versa.
web-1     |
web-1     | For more details and instructions, see https://go.orbstack.dev/multiarch
```

But it's probably an improvement from what's there, so I'm glad to merge it. To be honest, I've really avoided Docker for years and am totally out of my depth with its… quirks… so this part of the OSS project is probably best driven by folks who know what's going on here. I'll  try to learn more about it!

**Comment by anup39** [comment]
I am not deeply experienced in container deployment. I simply want to configure it so that I can deploy it easily without worrying about OS dependencies and Node version. The error you get  can be fixed by specifying the platform in the base image. I will add this into next PR , also i want to configure it in a way that i can use in production also so i will look around this part in upcoming days.

``` FROM --platform=linux/amd64 node:20-slim ```

Plus intially i setup the project the mapbox token didnot work, so i add that varaible into env file so it can be a option for user to use their token if they have, which i forgot to mention you last time.

**Pull request merged**
